### ISSUE TITLE
Add support for debug events

### ISSUE THREAD

**Issue by andyrichardson** [FormidableLabs/urql-devtools-exchange#20]
## About

Dispatch debug events to the devtools extension

https://github.com/FormidableLabs/urql/pull/

## Todo
 - [x] Migrate to _@urql/core_
 - [ ] Update devtools request pane 
 - [ ] Update peer dependency to match new _@urql/core_ version
